spring:
  datasource:
    url: jdbc:mysql://localhost:3306/crowdfunding
    username: root
    password: passer
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: truey
  session:
    jdbc:
      initialize-schema: always



server:
  error:
    include-message: always